
select * from netflix_data

1,CONTENT STRATERGY ANALYSIS

WHICH TYPE HAS THE HIGHEST COLLECTION ANS : MOVIE-5952, TV SHOW-249 
SELECT type, COUNT(*) AS total_titles 
FROM netflix_data 
GROUP BY type 
ORDER BY total_titles DESC

DOES NETFLIX SHIFTING TOWARDS TV SHOWS ANS : NO, BUT TV SHOWS ARE INCREASING AFTER 2019 IN A SMALL MARGIN
SELECT year_added, type, COUNT(*) AS total_titles 
FROM netflix_data 
GROUP BY year_added, type 

2,NETFLIX GROWTH & EXPANSION

WHICH YEAR THE MOST TTLES ADDED ANS : 2019
SELECT year_added, COUNT(*) AS titles_added
FROM netflix_data
GROUP BY year_added
ORDER BY titles_added DESC;

WHICH MONTH HAS MOST RELEASES ANS : JULY HAS THE MOST RELEASES FOLLOWED BY DECEMBER
SELECT month_added, COUNT(*) AS releases
FROM netflix_data
GROUP BY month_added
ORDER BY releases DESC;

3, CATALOG FRESHNESS STRATEGY

WHICH CONTENT CATEGORY DOMINATES ANS : NEW CONTENT DOMINATES THE MOST
SELECT content_category, COUNT(*) AS total_titles
FROM netflix_data
GROUP BY content_category
ORDER BY total_titles DESC;

WHAT IS THE AVG DURATION TAKEN TO RELEASE AND PUBLISH THE MOVIE IN NETFLIX ANS : THE AVG DURATION TAKEN IS 6 YEARS
SELECT ROUND(AVG(content_age)) AS avg_year_gap
FROM netflix_data;

4. GENRE INVESTMENT STRATEGY

WHICH IS THE TOP GENRE ANS : DRAMAS IS AT THE TOP
SELECT genre, COUNT(*) AS total_titles
FROM netflix_data
GROUP BY genre
ORDER BY total_titles DESC
LIMIT 10;

5. GLOBAL CONTENT STRATEGY

WHICH COUNTRY HAS THE MOST TITLES ANS : US HAS THE MOST TITLES 
SELECT country, COUNT(*) AS total_titles
FROM netflix_data
GROUP BY country
ORDER BY total_titles DESC;

6. AUDIENCE TARGETING STRATEGY

WHICH RATING DOMINANT THE MOST ANS : TV-MA DOMINATES THE MOST WHICH MEANS MATURE AUDIANCE (AGE ABOVE 17 CONTENT)
SELECT rating, COUNT(*) AS total_titles
FROM netflix_data
GROUP BY rating
ORDER BY total_titles DESC;

















